name: Tianruiapp
options:
  minimumXcodeGenVersion: 2.45.0
settings:
  base:
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: 8Q92DEV7VD
targets:
  Tianruiapp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Tianruiapp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: xiaochao.com
        INFOPLIST_FILE: Tianruiapp/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 8Q92DEV7VD
        CODE_SIGN_IDENTITY: Apple Development
        PROVISIONING_PROFILE_SPECIFIER: ""
    scheme:
      testTargets:
        - TianruiappTests
  TianruiappTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - TianruiappTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Tianruiapp
